{application,fast_xml,
             [{description,"Fast Expat-based Erlang / Elixir XML parsing library"},
              {vsn,"1.1.49"},
              {modules,[fast_xml,fxml,fxml_gen,fxml_gen_pt,fxml_stream,
                        fxml_sup,fxmlrpc,fxmlrpc_codec,
                        fxmlrpc_codec_external]},
              {registered,[]},
              {applications,[kernel,stdlib,p1_utils]},
              {mod,{fast_xml,[]}},
              {files,["src/","lib/","c_src/fxml.c","c_src/fxml_stream.c",
                      "include/","priv/lib/.keepme","configure","mix.exs",
                      "mix.lock","Makefile.mix","rebar.config",
                      "rebar.config.script","vars.config.in","README.md",
                      "LICENSE.txt"]},
              {licenses,["Apache 2.0"]},
              {links,[{"Github","https://github.com/processone/fast_xml"}]}]}.
