\ 4tH library - Characters - Copyright 2010,2012 J.L. Bezemer
\ You can redistribute this file and/or modify it under
\ the terms of the GNU General Public License

[UNDEFINED] '?' [IF]
  char ! CONSTANT '!'                  \ character '!'
  char " CONSTANT '"'                  \ character '"'
  char # CONSTANT '#'                  \ character '#'
  char $ CONSTANT '$'                  \ character '$'
  char % CONSTANT '%'                  \ character '%'
  char & CONSTANT '&'                  \ character '&'
  char ' CONSTANT '''                  \ character '''
  char ( CONSTANT '('                  \ character '('
  char ) CONSTANT ')'                  \ character ')'
  char * CONSTANT '*'                  \ character '*'
  char + CONSTANT '+'                  \ character '+'
  char , CONSTANT ','                  \ character ','
  char - CONSTANT '-'                  \ character '-'
  char . CONSTANT '.'                  \ character '.'
  char / CONSTANT '/'                  \ character '/'
  char 0 CONSTANT '0'                  \ character '0'
  char 1 CONSTANT '1'                  \ character '1'
  char 2 CONSTANT '2'                  \ character '2'
  char 3 CONSTANT '3'                  \ character '3'
  char 4 CONSTANT '4'                  \ character '4'
  char 5 CONSTANT '5'                  \ character '5'
  char 6 CONSTANT '6'                  \ character '6'
  char 7 CONSTANT '7'                  \ character '7'
  char 8 CONSTANT '8'                  \ character '8'
  char 9 CONSTANT '9'                  \ character '9'
  char : CONSTANT ':'                  \ character ':'
  char ; CONSTANT ';'                  \ character ';'
  char < CONSTANT '<'                  \ character '<'
  char = CONSTANT '='                  \ character '='
  char > CONSTANT '>'                  \ character '>'
  char ? CONSTANT '?'                  \ character '?'
  char @ CONSTANT '@'                  \ character '@'
  char [ CONSTANT '['                  \ character '['
  char \ CONSTANT '\'                  \ character '\'
  char ] CONSTANT ']'                  \ character ']'
  char ^ CONSTANT '^'                  \ character '^'
  char _ CONSTANT '_'                  \ character '_'
  char ` CONSTANT '`'                  \ character '`'
  char { CONSTANT '{'                  \ character '{'
  char | CONSTANT '|'                  \ character '|'
  char } CONSTANT '}'                  \ character '}'
  char ~ CONSTANT '~'                  \ character '~'

( Since 4tH is case insensitive, you cannot use the same name to represent )
( both the upper- and the lower-case characters. Default, the constant     )
( represents an upper-case character, but you can override that behavior   )
( with the pragma FORCELOWERCONSTANTS.                                     )

[DEFINED] forcelowerconstants [IF]
  char a CONSTANT 'a'                  \ character 'a'
  char b CONSTANT 'b'                  \ character 'b'
  char c CONSTANT 'c'                  \ character 'c'
  char d CONSTANT 'd'                  \ character 'd'
  char e CONSTANT 'e'                  \ character 'e'
  char f CONSTANT 'f'                  \ character 'f'
  char g CONSTANT 'g'                  \ character 'g'
  char h CONSTANT 'h'                  \ character 'h'
  char i CONSTANT 'i'                  \ character 'i'
  char j CONSTANT 'j'                  \ character 'j'
  char k CONSTANT 'k'                  \ character 'k'
  char l CONSTANT 'l'                  \ character 'l'
  char m CONSTANT 'm'                  \ character 'm'
  char n CONSTANT 'n'                  \ character 'n'
  char o CONSTANT 'o'                  \ character 'o'
  char p CONSTANT 'p'                  \ character 'p'
  char q CONSTANT 'q'                  \ character 'q'
  char r CONSTANT 'r'                  \ character 'r'
  char s CONSTANT 's'                  \ character 's'
  char t CONSTANT 't'                  \ character 't'
  char u CONSTANT 'u'                  \ character 'u'
  char v CONSTANT 'v'                  \ character 'v'
  char w CONSTANT 'w'                  \ character 'w'
  char x CONSTANT 'x'                  \ character 'x'
  char y CONSTANT 'y'                  \ character 'y'
  char z CONSTANT 'z'                  \ character 'z'
[ELSE]
  char A CONSTANT 'A'                  \ character 'A'
  char B CONSTANT 'B'                  \ character 'B'
  char C CONSTANT 'C'                  \ character 'C'
  char D CONSTANT 'D'                  \ character 'D'
  char E CONSTANT 'E'                  \ character 'E'
  char F CONSTANT 'F'                  \ character 'F'
  char G CONSTANT 'G'                  \ character 'G'
  char H CONSTANT 'H'                  \ character 'H'
  char I CONSTANT 'I'                  \ character 'I'
  char J CONSTANT 'J'                  \ character 'J'
  char K CONSTANT 'K'                  \ character 'K'
  char L CONSTANT 'L'                  \ character 'L'
  char M CONSTANT 'M'                  \ character 'M'
  char N CONSTANT 'N'                  \ character 'N'
  char O CONSTANT 'O'                  \ character 'O'
  char P CONSTANT 'P'                  \ character 'P'
  char Q CONSTANT 'Q'                  \ character 'Q'
  char R CONSTANT 'R'                  \ character 'R'
  char S CONSTANT 'S'                  \ character 'S'
  char T CONSTANT 'T'                  \ character 'T'
  char U CONSTANT 'U'                  \ character 'U'
  char V CONSTANT 'V'                  \ character 'V'
  char W CONSTANT 'W'                  \ character 'W'
  char X CONSTANT 'X'                  \ character 'X'
  char Y CONSTANT 'Y'                  \ character 'Y'
  char Z CONSTANT 'Z'                  \ character 'Z'
[THEN]
[THEN]
